Update custom_schema_types.md
vinejs/vinejs.dev pull request #19
Opened 2024-05-04 23:14 UTC by ShahriarKh

### 📚 Description

Added type imports in custom schema types section.

2024-05-05 06:20 UTC, RomainLanz requested changes

2024-05-05 06:20 UTC, RomainLanz commented on content/docs/extend/custom_schema_types.md
> +import { FieldOptions, Validation } from '@vinejs/vine/types'
```suggestion
import type { FieldOptions, Validation } from '@vinejs/vine/types'
```

2024-05-11 18:12 UTC, ShahriarKh commented on content/docs/extend/custom_schema_types.md
> +import { FieldOptions, Validation } from '@vinejs/vine/types'
Is it just for better readability?

2024-05-15 09:21 UTC, merged

2024-05-15 09:22 UTC, RomainLanz commented
Thanks!